name: Docker Image
on:
    push:
      branches:
        - main
    workflow_dispatch:
jobs:
    push-image:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
        - run: |
            docker build . --tag ghcr.io/${{github.repository}}:latest
            docker push ghcr.io/${{github.repository}}:latest