name: Docker Image
on:
    push:
      branches:
        - main
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: easimon/maximize-build-space@v8
          with:
            root-reserve-mb: 512
            swap-size-mb: 1024
            remove-dotnet: true
            remove-android: true
            remove-codeql: true
            remove-haskell: true
            remove-docker-images: true
        - uses: actions/checkout@v4
        - uses: docker/setup-qemu-action@v3
        - uses: docker/setup-buildx-action@v3
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
        - uses: docker/build-push-action@v5
          with:
              context: .
              platforms: linux/amd64,linux/arm64
              push: true
              tags: ghcr.io/${{ github.repository }}:latest