name: Docker Image
on:
    push:
      branches:
        - main
    workflow_dispatch:
jobs:
    push-image:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: '3.8'
            cache: 'pip'
            cache-dependency-path: |
              **/requirements*.txt
        - uses: docker/setup-buildx-action@v3
        - name: Cache Docker layers
          uses: tespkg/actions-cache@v1
          with:
            endpoint: "127.0.0.1"
            port: 8333
            insecure: true
            accessKey: "ghrunner"
            secretKey: ${{ secrets.SEAWEED_AUTH }}
            bucket: gh
            region: local
            use-fallback: true
            path: .buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
              context: .
              push: false
              tags: ghcr.io/${{github.repository}}:latest
              cache-from: type=local,src=/tmp/.buildx-cache
              cache-to: type=local,dest=/tmp/.buildx-cache-new
        - name: Move cache
          run: |
            rm -rf /tmp/.buildx-cache
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache